spring:
  application:
    name: billmanager
server:
  port: 8090
logging:
  level:
    org.springframework.boot.autoconfigure: INFO

auth:
  data:
    billing.spacecore.pro: ${SPACE_CORE_AUTH_DATA}
    billing.firstbyte.ru: ${FIRST_BYTE_AUTH_DATA}
    bill.ufo.hosting: ${UFO_AUTH_DATA}
    bill.yacolo.net: ${YACOLO_AUTH_DATA}
    vps.datacheap.ru: ${DATACHEAP_AUTH_DATA}

